### ISSUE TITLE
The tab switching shortcuts J and K aren't surfaced in the help dialog or README

### ISSUE THREAD

**Issue by philc** [philc/sheetkeys#36]

**Comment by qadzek** [comment]
A bit related, but not worth opening another issue: `C-S-j    Move rows down` would be clearer than `C-J    Move rows down` in my opinion. I couldn't get it working for some time, before I realised `Ctrl+Shift+j` was needed.

Also, for some reason `README.md` shows key bindings like `;,w,f  Toggle full screen`, while just `;wf` suffices. The help dialog doesn't show the unnecessary commas.

Thanks a lot for this amazing extension!

**Comment by jparoz** [comment]
@infinitewhileloop, I'd say it might be worth opening another issue for that stuff; it's a larger question of what should be the notation used in documentation.

I agree that the commas are unnecessary, as well as possibly confusing. What if the default binding for a shortcut was a comma? I like `;wf`, because that's what you'd see in Vim's help, and that's what is seen in SheetKeys' help (within separated boxes, like `;` `w` `f`).

I'm not as certain about the `C-J` vs `C-S-j` question. The two notations seem to be generally interchangeable in Vim. I think there's a case to be made that `C-S-j` is clearer, although I'm used to using the `C-J` notation. 🤷🏻

**Comment by philc** [comment]
I've removed the commas between the key mappings shown in the README. I agree that it's confusing, especially since the help dialog shows it another way. The commas were an artifact of how SheetKeys used to previously store its configuration.

I don't have a strong opinion about `C-S-j` vs. `C-J`. Anyone else who comes across this issue, please feel free to weigh in.
