### ISSUE TITLE
All shortcuts for merging/unmerging don't work

### ISSUE THREAD

**Issue by ayanokato** [philc/sheetkeys#37]
Exactly as the title states, all of the binds for merging and unmerging refuse to work, `; m a` doesn't seem to do anything with merging all cells, neither does `; m u` to unmerge. I even tried rebinding them to `<C-m>` but that doesn't work either.

**Comment by maarinku** [comment]
I've figured out the case of this is because my browser window wasn't maximized, it was only on half of the screen, and to get it to work again I had to maximize it and then reload the tab.

**Comment by jparoz** [comment]
I can reproduce this as described. If the page is loaded maximised, the merge hotkeys work straight away; but if the page is loaded with a width lower than a certain threshold, the hotkeys don't work. This state is sticky, up to reloading the page.

One way to make the hotkeys work in the less-wide state is to navigate in the menu: Format > Merge cells. You don't even need to select "Merge all" or any other option, simply opening this submenu causes the hotkeys to work correctly.

I suspect that this has something to do with the menus not being loaded in the way that SheetKeys expects, because when the window is less wide, the "Format" menu (and others) may not be drawn to the screen. Although, even if "Format" is visible, the hotkeys still may not work; the threshold seems to be somewhere just past when the ellipsis disappears.

I'll have a poke around and see if I can figure it out, but I'm still getting my head around how the menuing works.

**Comment by jparoz** [comment]
Seems like the actual threshold was the merge submenu in the toolbar. #43 fixes this bug.
