### ISSUE TITLE
Shortcut doesn't seem to work

### ISSUE THREAD

**Issue by malevinson** [philc/sheetkeys#4]
https://github.com/philc/sheetkeys/blob/bab64754c8d08c549b5849e6c7747c1d398223c2/content_scripts/commands.js#L97

What is this shortcut exactly?
Command + j and control + J both don't work on my mac. All other shortcuts work.

**Comment by philc** [comment]
It's typed as shift+control+j (I'm also using a Mac).

**Comment by malevinson** [comment]
Thanks for the quick reply. 

This still isn't working for me. I don't think any other tools are interfering.

**Comment by wuqui** [comment]
Doesn't work for me either. I'm also on a Mac. In fact only very few of the keys work for me, some from normal mode such as moving around and inserting, appending plus visual selection. Are we doing something wrong?

**Comment by philc** [comment]
I use this every day on a Mac and naturally, every shortcut works for me.

I'm not sure how to help further without being able to reproduce it myself, other than adding verbose logging and hoping that this signals the error. If someone with this issue has the determination to add debugging statements and further isolate the issue, that would be helpful (and may make the issue, and fix, immediately obvious).

**Comment by wuqui** [comment]
It must be awesome to have all these shortcuts available. I found myself inadvertently trying to use Vim bindings to move around a couple of times, so it's a great idea for an add-on!

Could the problem be due to using a foreign (German) keyboard / version of Google sheets? Some of the keys work (such as `a`,  `i`, `v`) so first I thought just the "more complex" ones involving `ctrl` wouldn't work, but unfortunately also `s` and `o` don't work which would be immensely useful.

Unfortunately I don't know enough to add debugging statements etc. to your code.

**Comment by malevinson** [comment]
You are correct @philc they do work (on my work mac). Not sure what the problem is on my personal mac.

Thank you for this wonderful extension. I will close the ticket.

**Comment by wuqui** [comment]
Anything else I could try? Would really like to use this a lot!
